//HintName: BaseAssertions`2.g.cs
// <auto-generated />
#pragma warning disable CS8019, CS8933
#nullable restore
using mazharenko.FluentAssertions.Eventual;
using FluentAssertions.Primitives;

namespace Namespace
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.FluentAssertions.Eventual", "4.1.0")]
	public abstract class BaseAssertions_Eventual<TSubject, TAssertions>
		where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
	{
		private readonly BaseAssertions<TSubject, TAssertions> underlying;
		private readonly System.TimeSpan timeout;
		private readonly System.TimeSpan delay;
		public BaseAssertions_Eventual(BaseAssertions<TSubject, TAssertions> underlying, System.TimeSpan timeout, System.TimeSpan delay)
		{
			this.underlying = underlying;
			this.timeout = timeout;
			this.delay = delay;
		}
	}
}
#pragma warning restore CS8019, CS8933
