//HintName: BaseAssertions`2.g.cs
// <auto-generated />
using mazharenko.FluentAssertions.Eventual;
using FluentAssertions;
using FluentAssertions.Execution;
using FluentAssertions.Primitives;

namespace Namespace
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.FluentAssertions.Eventual", "4.0.1")]
	public static class BaseAssertions_Eventual_2_Extensions
	{
		public static BaseAssertions_Eventual<TSubject, TAssertions> Eventually<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return Eventually(underlying, System.TimeSpan.FromSeconds(5), System.TimeSpan.FromMilliseconds(100));
		}

		public static BaseAssertions_Eventual<TSubject, TAssertions> EventuallyLong<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return Eventually(underlying, System.TimeSpan.FromSeconds(20), System.TimeSpan.FromMilliseconds(500));
		}

		public static BaseAssertions_Eventual<TSubject, TAssertions> Eventually<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying, System.TimeSpan timeout, System.TimeSpan delay)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return new BaseAssertions_Eventual<TSubject, TAssertions>(underlying, timeout, delay);
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.FluentAssertions.Eventual", "4.0.1")]
	public class BaseAssertions_Eventual<TSubject, TAssertions>
		where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
	{
		private readonly BaseAssertions<TSubject, TAssertions> underlying;
		private readonly System.TimeSpan timeout;
		private readonly System.TimeSpan delay;
		public BaseAssertions_Eventual(BaseAssertions<TSubject, TAssertions> underlying, System.TimeSpan timeout, System.TimeSpan delay)
		{
			this.underlying = underlying;
			this.timeout = timeout;
			this.delay = delay;
		}
	}
}