//HintName: BaseAssertions`2.g.cs
// <auto-generated />
#pragma warning disable CS8019, CS8933
#nullable restore
using mazharenko.FluentAssertions.Eventual;
using FluentAssertions.Primitives;

namespace Namespace
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.FluentAssertions.Eventual", "<version>"]
	public static class BaseAssertions_Eventual_2_Extensions
	{
		/// <summary>
		/// Returns a <see cref="T:Namespace.BaseAssertions_Eventual`2"/> wrapper that adds waiting to the current <see cref="T:Namespace.BaseAssertions`2"/>
		/// </summary>
		public static BaseAssertions_Eventual<TSubject, TAssertions> Eventually<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return Eventually(underlying, System.TimeSpan.FromSeconds(5), System.TimeSpan.FromMilliseconds(100));
		}

		/// <summary>
		/// Returns a <see cref="T:Namespace.BaseAssertions_Eventual`2"/> wrapper that adds waiting to the current <see cref="T:Namespace.BaseAssertions`2"/>
		/// </summary>
		public static BaseAssertions_Eventual<TSubject, TAssertions> EventuallyLong<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return Eventually(underlying, System.TimeSpan.FromSeconds(20), System.TimeSpan.FromMilliseconds(500));
		}

		/// <summary>
		/// Returns a <see cref="T:Namespace.BaseAssertions_Eventual`2"/> wrapper that adds waiting to the current <see cref="T:Namespace.BaseAssertions`2"/>
		/// </summary>
		public static BaseAssertions_Eventual<TSubject, TAssertions> Eventually<TSubject, TAssertions>(this BaseAssertions<TSubject, TAssertions> underlying, System.TimeSpan timeout, System.TimeSpan delay)
			where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
		{
			return new BaseAssertions_Eventual<TSubject, TAssertions>(underlying, timeout, delay);
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.FluentAssertions.Eventual", "<version>"]
	public class BaseAssertions_Eventual<TSubject, TAssertions>
		where TSubject : class where TAssertions : BaseAssertions<TSubject, TAssertions>
	{
		private readonly BaseAssertions<TSubject, TAssertions> underlying;
		private readonly System.TimeSpan timeout;
		private readonly System.TimeSpan delay;
		public BaseAssertions_Eventual(BaseAssertions<TSubject, TAssertions> underlying, System.TimeSpan timeout, System.TimeSpan delay)
		{
			this.underlying = underlying;
			this.timeout = timeout;
			this.delay = delay;
		}
	}
}
#pragma warning restore CS8019, CS8933
